import pygame

class Scene:
    def __init__(self) -> None: ...
    def on_exit(self, **kwargs) -> None: ...
    def on_enter(self, **kwargs) -> None: ...
    def update(self, delta: float) -> None: ...
    def draw(self, surface: pygame.Surface) -> None: ...
